apiVersion: v1
kind: ConfigMap
metadata:
  name: emailrss-config
  namespace: emailrss
data:
  config.yaml: |
    imap:
      # use environment variables for these 3 instead
      # EMAILRSS_IMAP_HOST, EMAILRSS_IMAP_USERNAME, EMAILRSS_IMAP_PASSWORD
      host: "imap.example.com"
      username: "user@example.com"
      password: "your-password"
      port: 993
      timeout: 30  # Connection timeout in seconds (default: 30)
      tls: true
      folders:
        "INBOX": "inbox"
        "INBOX/Important": "important"
        "INBOX/Work": "work"

    database:
      path: "/data/db/emailrss.db"

    rss:
      output_dir: "/data/feeds"
      title: "Email RSS Feeds"
      base_url: "http://emailrss-service:8080"
      # Content length limits (optional)
      max_html_content_length: 8000      # Max chars for processing HTML content
      max_text_content_length: 3000      # Max chars for processing text content
      max_rss_html_length: 5000          # Max chars for RSS HTML content
      max_rss_text_length: 2900          # Max chars for RSS text content
      max_summary_length: 300            # Max chars for item summaries
      remove_css: false                  # Remove CSS styling, HTML comments, and presentation attributes from HTML emails
                                         # Removes: <style> blocks, style= attributes, class=, id=, bgcolor=, width=, height=,
                                         # align=, valign=, border=, cellpadding=, cellspacing=, color=, face=, size=, charset=

    server:
      host: "0.0.0.0"
      port: 8080

    # Debug options (optional, all default to false/disabled)
    debug:
      enabled: false                                # Enable debug mode
      raw_messages_dir: "/data/debug/raw_messages"  # Directory for raw IMAP messages
      save_raw_messages: false                      # Save raw IMAP messages to disk
      max_raw_messages: 100                         # Maximum number of raw messages to keep

    # Processing options (optional, for performance tuning)
    processing:
      max_workers: 5                                # Maximum concurrent workers for message processing (default: 5, max: 20)
