apiVersion: batch/v1
kind: CronJob
metadata:
  name: emailrss-processor
  namespace: emailrss
spec:
  schedule: "*/5 * * * *"  # Every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: emailrss-processor
            image: emailrss:latest
            imagePullPolicy: Always
            command: ["./emailrss", "process", "--once", "-c", "/data/config.yaml"]
            volumeMounts:
            - name: config-volume
              mountPath: /data/config.yaml
              subPath: config.yaml
            - name: data-volume
              mountPath: /data
            env:
            - name: TZ
              value: "UTC"
            resources:
              requests:
                memory: "64Mi"
                cpu: "50m"
              limits:
                memory: "256Mi"
                cpu: "200m"
          volumes:
          - name: config-volume
            configMap:
              name: emailrss-config
          - name: data-volume
            persistentVolumeClaim:
              claimName: emailrss-data
          restartPolicy: OnFailure